spring:
  swagger:
    enabled: true
  jackson:
    default-property-inclusion: non-empty
  profiles:
    active:
      - api

server:
  port: 9002
globalegrow:
  cors:
    - path-pattern: '/**'
      allow-credentials: true
      allowed-origins: 
        - '*'
      allowed-headers:
        - abcdef
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH