server:
  port: 0
  
spring:
  application:
    admin:
      enabled: true
    name: demo-async-rabbitmq
 
  rabbitmq:
    host: 10.40.6.89
    port: 5672
    username: iss_test
    password: iss_test
    virtual-host: ISS
    cache:
      channel:
        size: 20
      connection:
        mode: channel
    listener:
      simple:
        auto-startup: true
        concurrency: 10
        acknowledge-mode: auto
        max-concurrency: 100
    batch:
      s: 
        host: ss
globalegrow:
  task:
    core-pool-size: 2000
    max-pool-size: 2000
    keep-alive-seconds: 0
  rabbit:
    client-count: 5
    concurrency: 1000
    rabbit-template-bean-name: rabbitTemplate
    exchange-name: amq.direct
    queue-names:
      - sync-queue-iss-0
      - sync-queue-iss-1
      - sync-queue-iss-2
